// Script para carga inicial de dados (Executar no console do navegador se necessário)
const initialItems = [
    { nome: "Geladeira", categoria: "ITENS CAROS" },
    { nome: "Maquina de lavar", categoria: "ITENS CAROS" },
    { nome: "Televisão 75 polegadas", categoria: "ITENS CAROS", comprado: true, valor: 3500, usuario: "João/Felipe" },
    { nome: "Forno eletrico bom", categoria: "ITENS CAROS" },
    { nome: "Microondas", categoria: "ITENS CAROS" },
    { nome: "Panificadora", categoria: "ITENS CAROS" },
    { nome: "Lava louça", categoria: "ITENS CAROS" },
    { nome: "Mesa e cadeiras", categoria: "ITENS CAROS" },
    { nome: "Sofá", categoria: "ITENS CAROS" },
    { nome: "Fogão indução", categoria: "ITENS CAROS" },
    { nome: "Panelas indução", categoria: "ITENS CAROS" },
    { nome: "Aparador sala", categoria: "ITENS CAROS" },
    
    { nome: "Tábua de corte de vidro", categoria: "COZINHA" },
    { nome: "Jogo de facas com cepo", categoria: "COZINHA" },
    { nome: "Conjunto de talheres", categoria: "COZINHA" },
    { nome: "Copos para água/suco", categoria: "COZINHA" },
    { nome: "Xícaras para café/chá", categoria: "COZINHA" },
    { nome: "Potes para armazenamento - Tupperware (12 potes)", categoria: "COZINHA" },
    { nome: "Potes para armazenamento - Tupperware (8 potes)", categoria: "COZINHA" },
    { nome: "Escorredor de louça", categoria: "COZINHA" },
    { nome: "Escorredor de macarrão", categoria: "COZINHA" },
    { nome: "Lixeira", categoria: "COZINHA" },
    { nome: "Abridor de latas/garrafas", categoria: "COZINHA" },
    { nome: "Espremedor de limão/laranja", categoria: "COZINHA" },
    { nome: "Ralador", categoria: "COZINHA" },
    { nome: "Colher de pau", categoria: "COZINHA" },
    { nome: "Pegador de macarrão", categoria: "COZINHA" },
    { nome: "Espátula", categoria: "COZINHA" },
    { nome: "Concha", categoria: "COZINHA" },
    { nome: "Escumadeira", categoria: "COZINHA" },
    { nome: "Descascador de legumes", categoria: "COZINHA" },
    { nome: "Forma para bolo", categoria: "COZINHA" },
    { nome: "Pano de prato", categoria: "COZINHA" },
    { nome: "Jarra para água/suco", categoria: "COZINHA" },
    { nome: "Filtro de água", categoria: "COZINHA" },
    { nome: "Garrafa térmica", categoria: "COZINHA" },
    { nome: "Esponja", categoria: "COZINHA" },
    { nome: "forma para fazer hamburguer", categoria: "COZINHA" },
    { nome: "seladora", categoria: "COZINHA" },
    { nome: "amassador de batata", categoria: "COZINHA" },
    { nome: "Frigideiras (diferentes tamanhos)", categoria: "COZINHA" },
    { nome: "Pratos (rasos e fundos)", categoria: "COZINHA" },
    { nome: "Chaleira Eletrica", categoria: "COZINHA" },
    { nome: "Sanduicheira", categoria: "COZINHA" },
    { nome: "Liquidificador", categoria: "COZINHA" },
    { nome: "Mixer", categoria: "COZINHA" },
    { nome: "Cafeteira", categoria: "COZINHA" },

    { nome: "Tapete", categoria: "SALA DE ESTAR" },
    { nome: "Almofadas", categoria: "SALA DE ESTAR" },
    { nome: "Cortinas", categoria: "SALA DE ESTAR" },
    { nome: "Luminárias", categoria: "SALA DE ESTAR" },
    { nome: "Porta-controle", categoria: "SALA DE ESTAR" },
    { nome: "Manta para sofá", categoria: "SALA DE ESTAR" },

    { nome: "Toalha de mesa", categoria: "SALA DE JANTAR" },
    { nome: "Jogo americano", categoria: "SALA DE JANTAR" },
    { nome: "Guardanapos de tecido", categoria: "SALA DE JANTAR" },
    { nome: "Porta-guardanapos", categoria: "SALA DE JANTAR" },
    { nome: "Fruteira", categoria: "SALA DE JANTAR" },
    { nome: "Jogos de taças (vinho, champagne)", categoria: "SALA DE JANTAR" },
    { nome: "Pratos de sobremesa", categoria: "SALA DE JANTAR" },
    { nome: "Travessas para servir", categoria: "SALA DE JANTAR" },
    { nome: "Jogo de jantar para ocasiões especiais", categoria: "SALA DE JANTAR" },

    { nome: "Jogo de lençóis (pelo menos 2)", categoria: "QUARTO" },
    { nome: "Espelho", categoria: "QUARTO" },
    { nome: "Abajur", categoria: "QUARTO" },
    { nome: "Cortinas", categoria: "QUARTO" },
    { nome: "Tapete", categoria: "QUARTO" },
    { nome: "Cabide", categoria: "QUARTO" },
    { nome: "Guarda-roupa", categoria: "QUARTO" },
    { nome: "Criado-mudo", categoria: "QUARTO" },
    { nome: "Edredom/cobertor", categoria: "QUARTO" },

    { nome: "Jogo de toalhas (banho, rosto e mão)", categoria: "BANHEIRO" },
    { nome: "Tapete", categoria: "BANHEIRO" },
    { nome: "Lixeira", categoria: "BANHEIRO" },
    { nome: "Porta-escova de dentes", categoria: "BANHEIRO" },
    { nome: "Saboneteira", categoria: "BANHEIRO" },
    { nome: "Porta papel higiênico", categoria: "BANHEIRO" },
    { nome: "Escova sanitária", categoria: "BANHEIRO" },
    { nome: "Cesto para roupa suja", categoria: "BANHEIRO" },
    { nome: "Espelho", categoria: "BANHEIRO" },
    { nome: "Chuveiro", categoria: "BANHEIRO" },

    { nome: "Varal", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Tábua de passar", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Cesto para roupas", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Pregadores", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Escova para lavar roupas", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Cabideiro para secagem", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Vassoura", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Rodo", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Pá de lixo", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Balde", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Esfregão", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Flanelas", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Luvas", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Aspirador de pó", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Escada pequena", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Organizador de produtos de limpeza", categoria: "LAVANDEIRA / LIMPEZA" },
    { nome: "Ferro de passar", categoria: "LAVANDEIRA / LIMPEZA" },

    { nome: "Kit de ferramentas básicas", categoria: "FERRAMENTAS" },
    { nome: "Extintor de incêndio", categoria: "FERRAMENTAS" },
    { nome: "Kit de primeiros socorros", categoria: "FERRAMENTAS" },
    { nome: "Lanterna", categoria: "FERRAMENTAS" },
    { nome: "Alarme/câmera de segurança", categoria: "FERRAMENTAS" }
];

async function seed() {
    console.log("Iniciando carga de dados...");
    for (const item of initialItems) {
        await db.collection('enxoval').add({
            nome: item.nome,
            categoria: item.categoria,
            comprado: item.comprado || false,
            valor: item.valor || 0,
            usuario: item.usuario || ""
        });
        console.log(`Adicionado: ${item.nome}`);
    }
    console.log("Carga finalizada!");
}

// Para executar, basta chamar seed() no console do navegador após o Firebase carregar.
